doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'

        types:
            user_id: 'App\Domain\ValueObject\UserId'
            chat_message_id: 'App\Domain\ValueObject\ChatMessageId'
            chat_room_id: 'App\Domain\ValueObject\ChatRoomId'
            event_id: 'App\Domain\ValueObject\EventId'
            ticket_id: 'App\Domain\ValueObject\TicketId'
            seat_id: 'App\Domain\ValueObject\SeatId'
            venue_id: 'App\Domain\ValueObject\VenueId'
            payment_id: 'App\Domain\ValueObject\PaymentId'
            order_id: 'App\Domain\ValueObject\OrderId'
            event_seat_id: 'App\Domain\ValueObject\EventSeatId'
            message_text: 'App\Domain\ValueObject\MessageText'
            name: 'App\Domain\ValueObject\Name'
            email: 'App\Domain\ValueObject\Email'
            event_title: 'App\Domain\ValueObject\EventTitle'
            event_description: 'App\Domain\ValueObject\EventDescription'
            venue_address: 'App\Domain\ValueObject\VenueAddress'
            venue_city: 'App\Domain\ValueObject\VenueCity'
            venue_name: 'App\Domain\ValueObject\VenueName'
            seat_row: 'App\Domain\ValueObject\SeatRow'
            seat_number: 'App\Domain\ValueObject\SeatNumber'
            seat_sector: 'App\Domain\ValueObject\SeatSector'
            ticket_code: 'App\Domain\ValueObject\TicketCode'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/ORM'
                prefix: 'App\Domain\Entity'
                alias: App
            AppValueObject:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/ValueObject'
                prefix: 'App\Domain\ValueObject'
                alias: AppValueObject

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
