framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - validation
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Infrastructure\Messenger\OutboxMiddleware

        transports:
            sync: 'sync://'
            scheduler_default:
                dsn: 'schedule://default'
                retry_strategy:
                    max_retries: 0
            events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_EVENTS)%'
                options:
                    auto_setup: true
        routing:
            'App\Application\Message\SendPasswordResetEmail': events
            'App\Domain\Event\SeatsReservedEvent': events
            'App\Domain\Event\OrderPaidEvent': events
            'App\Domain\Event\OrderCancelledEvent': events
            'App\Domain\Event\OrderRefundedEvent': events
            'App\Domain\Event\EventCreatedEvent': events
            'App\Domain\Event\EventStatusChangedEvent': events
