security:
    password_hashers:
        App\Domain\Entity\User: 'auto'
        App\Infrastructure\Security\DomainUserAdapter: 'auto'

    providers:
        doctrine:
            id: App\Infrastructure\Security\DoctrineUserProvider

    role_hierarchy:
        ROLE_ADMIN: ROLE_MANAGER
        ROLE_MANAGER: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        admin_login:
            pattern: ^/api/admin/login
            stateless: true
            json_login:
                check_path: /api/admin/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        login:
            pattern: ^/api/auth/login$
            stateless: true
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        mock_bank:
            pattern: ^/mock-bank
            stateless: true
            provider: doctrine
            jwt: ~

        api:
            pattern: ^/api
            stateless: true
            provider: doctrine
            jwt: ~

    access_control:
        - { path: ^/api/webhooks/stripe, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/mock-bank, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/events, methods: [GET], roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/events, methods: [POST], roles: ROLE_MANAGER }
        - { path: ^/api/venues, methods: [POST], roles: ROLE_MANAGER }
        - { path: ^/api/venues, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
